### ISSUE TITLE
Graphile worker on supabase

### ISSUE THREAD

**Issue by tonyxiao** [monoppa/tokyo-monorepo#62]
In my supabase instance the worker doesn't seem to do anything (job just sits there without being run). Is there an extension / switch that needs to be turned on? What could it be because of?

**Comment by monoppa** [comment]
make sure to run apps/workers
and have the pgPool properly setup
I setup pgPool by having a `.env` file

```
# apps/workers/.env
PGUSER="postgres"
PGPASSWORD="postgres"
PGDATABASE="postgres"
PGPORT="54322"
```
